Repository SlimeCloud/SlimeBot, pull requests merged in 2023-09, with the labels that each got.

#117 Fdmds improve
  src/main/java/com/slimebot/commands/FdmdsCommand.java
Labels: bug

#116 Quote improve
  src/main/java/com/slimebot/commands/QuoteCommand.java
Labels: improve

#109 added Custom RankCard System
  README.md
  build.gradle
  src/main/java/com/slimebot/alerts/spotify/SpotifyListener.java
  src/main/java/com/slimebot/commands/FdmdsCommand.java
  src/main/java/com/slimebot/commands/QuoteCommand.java
  src/main/java/com/slimebot/commands/config/ConfigCommand.java
  src/main/java/com/slimebot/commands/config/engine/ConfigArrayPropertyCommand.java
  src/main/java/com/slimebot/commands/config/engine/ConfigArrayPropertyCommandType.java
  src/main/java/com/slimebot/commands/config/engine/ConfigCategoryCommand.java
  src/main/java/com/slimebot/commands/config/engine/ConfigFieldType.java
  src/main/java/com/slimebot/commands/config/setup/SetupCommand.java
  src/main/java/com/slimebot/commands/config/setup/StaffFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/ConfigFieldFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/SetupMainFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/SetupMenu.java
  src/main/java/com/slimebot/commands/level/card/CardCommand.java
  src/main/java/com/slimebot/commands/level/card/CardComponent.java
  src/main/java/com/slimebot/commands/level/card/frame/AvatarFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/BackgroundFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/BackgroundModalFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/BorderFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/CardFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/MainFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/ProgressbarColorFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/ProgressbarFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/ResetWarningFrame.java
  src/main/java/com/slimebot/commands/report/BlockCommand.java
  src/main/java/com/slimebot/commands/report/ReportCommand.java
  src/main/java/com/slimebot/commands/report/ReportListCommand.java
  src/main/java/com/slimebot/database/DataClass.java
  src/main/java/com/slimebot/events/LevelListener.java
  src/main/java/com/slimebot/events/MemberJoinListener.java
  src/main/java/com/slimebot/graphic/Graphic.java
  src/main/java/com/slimebot/graphic/ImageUtil.java
  src/main/java/com/slimebot/graphic/UIError.java
  src/main/java/com/slimebot/level/RankCard.java
  src/main/java/com/slimebot/level/profile/Avatar.java
  src/main/java/com/slimebot/level/profile/Background.java
  src/main/java/com/slimebot/level/profile/Border.java
  src/main/java/com/slimebot/level/profile/CardProfile.java
  src/main/java/com/slimebot/level/profile/Progressbar.java
  src/main/java/com/slimebot/level/profile/Style.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/main/config/guild/AssignRoleConfig.java
  src/main/java/com/slimebot/main/config/guild/GuildConfig.java
  src/main/java/com/slimebot/util/ColorUtil.java
  src/main/java/com/slimebot/util/Util.java
Labels: new feature

#118 Auto Message Delete
  build.gradle
  src/main/java/com/slimebot/commands/config/setup/AutoDeleteFrame.java
  src/main/java/com/slimebot/commands/config/setup/StaffFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/ConfigFieldFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/CustomSetupFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/SetupMainFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/SetupMenu.java
  src/main/java/com/slimebot/events/AutoDeleteListener.java
  src/main/java/com/slimebot/main/CommandPermission.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/main/config/guild/AutoDeleteConfig.java
  src/main/java/com/slimebot/main/config/guild/GuildConfig.java
  src/main/java/com/slimebot/util/Util.java
Labels: new feature

#122 Add Filter IMAGE_WITH_TEXT
  src/main/java/com/slimebot/main/config/guild/AutoDeleteConfig.java
Labels: new feature, improve

#123 Prohibit quoting messages in the quote channel
  src/main/java/com/slimebot/commands/QuoteCommand.java
Labels: bug, improve

#124 Level fix
  src/main/java/com/slimebot/commands/level/LeaderboardCommand.java
  src/main/java/com/slimebot/events/LevelListener.java
Labels: bug

#126 Rankcard fix
  src/main/java/com/slimebot/commands/level/RankCommand.java
  src/main/java/com/slimebot/commands/level/card/CardCommand.java
  src/main/java/com/slimebot/commands/level/card/frame/ResetWarningFrame.java
  src/main/java/com/slimebot/level/RankCard.java
Labels: bug, improve

#127 Improve Autodelete
  build.gradle
  src/main/java/com/slimebot/commands/QuoteCommand.java
  src/main/java/com/slimebot/commands/config/setup/AutoDeleteFrame.java
  src/main/java/com/slimebot/commands/config/setup/SetupCommand.java
  src/main/java/com/slimebot/commands/config/setup/StaffFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/ConfigFieldFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/CustomSetupFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/SetupMainFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/SetupMenu.java
  src/main/java/com/slimebot/events/AutoDeleteListener.java
  src/main/java/com/slimebot/events/LevelListener.java
  src/main/java/com/slimebot/main/config/guild/AutoDeleteConfig.java
  src/main/java/com/slimebot/main/config/guild/GuildConfig.java
Labels: new feature, improve

#128 Improve custom rank cards
  build.gradle
  src/main/java/com/slimebot/commands/level/card/CardCommand.java
  src/main/java/com/slimebot/commands/level/card/CardComponent.java
  src/main/java/com/slimebot/commands/level/card/frame/AvatarFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/BackgroundFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/BackgroundModalFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/BorderFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/CardFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/MainFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/ProgressbarColorFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/ProgressbarFrame.java
  src/main/java/com/slimebot/commands/level/card/frame/ResetWarningFrame.java
  src/main/java/com/slimebot/graphic/UIError.java
  src/main/java/com/slimebot/level/RankCard.java
  src/main/java/com/slimebot/level/profile/CardProfile.java
  src/main/java/com/slimebot/report/list/ReportBlockSet.java
  src/main/java/com/slimebot/report/list/ReportSet.java
  src/main/java/com/slimebot/util/ColorUtil.java
Labels: improve

#129 Team meeting
  src/main/java/com/slimebot/commands/config/engine/ConfigFieldType.java
  src/main/java/com/slimebot/commands/config/setup/MeetingInitFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/ConfigFieldFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/CustomSetupFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/SetupMenu.java
  src/main/java/com/slimebot/events/MeetingListener.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/main/config/guild/GuildConfig.java
  src/main/java/com/slimebot/main/config/guild/MeetingConfig.java
Labels: new feature

#130 Improve team meetings
  src/main/java/com/slimebot/events/MeetingListener.java
Labels: new feature, improve

#131 Improve logic for autodelete checks
  src/main/java/com/slimebot/events/AutoDeleteListener.java
Labels: improve

#132 Add null check for background url
  src/main/java/com/slimebot/level/RankCard.java
Labels: type: bug

#133 Try to fix Unknown Message and don't send delete feedback when the me…
  src/main/java/com/slimebot/events/AutoDeleteListener.java
  src/main/java/com/slimebot/main/Main.java
Labels: type: bug
