Repository SlimeCloud/SlimeBot, pull requests merged in 2023-07, with the labels that each got.

#40 FDMDS improvements
  src/main/java/com/slimebot/commands/Fdmds.java
  src/main/java/com/slimebot/utils/Config.java
Labels: bug, improve

#41 Use Message#getJumpUrl instead of manual building
  src/main/java/com/slimebot/report/contextmenus/MsgReport.java
Labels: improve

#48 Spotify channel fix
  src/main/java/com/slimebot/alerts/spotify/PodcastListener.java
  src/main/java/com/slimebot/alerts/spotify/SpotifyListener.java
Labels: bug

#37 Automatisches updaten der Staff Message
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/message/StaffMessage.java
Labels: feature

#58 HolidayAlert fixes
  src/main/java/com/slimebot/alerts/holidays/HolidayAlert.java
Labels: improve

#55 Rewrite Readme.md
  .github/pull_request_template.md
  .idea/runConfigurations/Package.xml
  .idea/runConfigurations/Run.xml
  README.md
Labels: improve

#46 Use Database
  .gitignore
  build.gradle
  config_preset
  src/main/java/com/slimebot/alerts/holidays/HolidayAlert.java
  src/main/java/com/slimebot/alerts/spotify/PodcastListener.java
  src/main/java/com/slimebot/alerts/spotify/SpotifyListener.java
  src/main/java/com/slimebot/alerts/spotify/SpotifyListenerManager.java
  src/main/java/com/slimebot/commands/BonkCommand.java
  src/main/java/com/slimebot/commands/BugCommand.java
  src/main/java/com/slimebot/commands/BulkAddRoleCommand.java
  src/main/java/com/slimebot/commands/ConfigCommand.java
  src/main/java/com/slimebot/commands/ContributorCommand.java
  src/main/java/com/slimebot/commands/FdmdsCommand.java
  src/main/java/com/slimebot/commands/InfoCommand.java
  src/main/java/com/slimebot/commands/PingCommand.java
  src/main/java/com/slimebot/commands/config/ConfigCommand.java
  src/main/java/com/slimebot/commands/config/FdmdsConfigCommand.java
  src/main/java/com/slimebot/commands/config/GuildConfigCommand.java
  src/main/java/com/slimebot/commands/config/SpotifyConfigCommand.java
  src/main/java/com/slimebot/commands/config/StaffConfigCommand.java
  src/main/java/com/slimebot/commands/report/BlockCommand.java
  src/main/java/com/slimebot/commands/report/DetailsCommand.java
  src/main/java/com/slimebot/commands/report/ListCommand.java
  src/main/java/com/slimebot/commands/report/MessageReportCommand.java
  src/main/java/com/slimebot/commands/report/ReportCommand.java
  src/main/java/com/slimebot/commands/report/ReportListCommand.java
  src/main/java/com/slimebot/commands/report/UserReportCommand.java
  src/main/java/com/slimebot/commands/report/UserReportSlashCommand.java
  src/main/java/com/slimebot/events/JoinListener.java
  src/main/java/com/slimebot/events/ReadyListener.java
  src/main/java/com/slimebot/events/StartupListener.java
  src/main/java/com/slimebot/events/TimeoutListener.java
  src/main/java/com/slimebot/main/CommandPermission.java
  src/main/java/com/slimebot/main/Database.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/main/SlimeEmoji.java
  src/main/java/com/slimebot/main/config/Config.java
  src/main/java/com/slimebot/main/config/DatabaseConfig.java
  src/main/java/com/slimebot/main/config/SpotifyConfig.java
  src/main/java/com/slimebot/main/config/SpotifyNotification.java
  src/main/java/com/slimebot/main/config/guild/FdmdsConfig.java
  src/main/java/com/slimebot/main/config/guild/GuildConfig.java
  src/main/java/com/slimebot/main/config/guild/SpotifyNotificationConfig.java
  src/main/java/com/slimebot/main/config/guild/StaffConfig.java
  src/main/java/com/slimebot/message/StaffMessage.java
  src/main/java/com/slimebot/report/Filter.java
  src/main/java/com/slimebot/report/Report.java
  src/main/java/com/slimebot/report/Status.java
  src/main/java/com/slimebot/report/Type.java
  src/main/java/com/slimebot/report/list/ReportBlockSet.java
  src/main/java/com/slimebot/report/list/ReportSet.java
  src/main/java/com/slimebot/utils/Checks.java
  src/main/java/com/slimebot/utils/Config.java
Labels: feature

#68 Add Documentation
  src/main/java/com/slimebot/commands/config/ConfigCommand.java
  src/main/java/com/slimebot/main/BuildInfo.java
  src/main/java/com/slimebot/main/CommandPermission.java
  src/main/java/com/slimebot/main/Database.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/main/config/Config.java
  src/main/java/com/slimebot/main/config/guild/GuildConfig.java
Labels: documentation

#69 Fix report listing
  src/main/java/com/slimebot/report/Report.java
  src/main/java/com/slimebot/report/list/ReportSet.java
Labels: bug, improve

#70 SetupCommand
  build.gradle
  src/main/java/com/slimebot/commands/SetupCommand.java
  src/main/java/com/slimebot/commands/config/StaffConfigCommand.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/main/config/guild/GuildConfig.java
Labels: feature

#71 GitHub issue
  build.gradle
  config_preset
  src/main/java/com/slimebot/commands/BugCommand.java
  src/main/java/com/slimebot/commands/BugContextCommand.java
  src/main/java/com/slimebot/commands/report/UserReportSlashCommand.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/main/config/Config.java
  src/main/java/com/slimebot/main/config/GitHubConfig.java
  src/main/java/com/slimebot/main/config/SpotifyConfig.java
  src/main/java/com/slimebot/main/config/SpotifyNotification.java
  src/main/resources/github_issue_template
Labels: feature

#67 new Level System
  build.gradle
  config_preset
  src/main/java/com/slimebot/commands/config/ConfigCommand.java
  src/main/java/com/slimebot/commands/level/LeaderboardCommand.java
  src/main/java/com/slimebot/commands/level/LevelCommand.java
  src/main/java/com/slimebot/commands/level/RankCommand.java
  src/main/java/com/slimebot/commands/level/add/AddLevelCommand.java
  src/main/java/com/slimebot/commands/level/add/AddXPCommand.java
  src/main/java/com/slimebot/commands/level/remove/RemoveLevelCommand.java
  src/main/java/com/slimebot/commands/level/remove/RemoveXPCommand.java
  src/main/java/com/slimebot/commands/level/reset/ResetAllCommand.java
  src/main/java/com/slimebot/commands/level/reset/ResetLevelCommand.java
  src/main/java/com/slimebot/commands/level/reset/ResetMessagesCommand.java
  src/main/java/com/slimebot/commands/level/reset/ResetXPCommand.java
  src/main/java/com/slimebot/graphic/CustomFont.java
  src/main/java/com/slimebot/graphic/Graphic.java
  src/main/java/com/slimebot/graphic/ImageUtil.java
  src/main/java/com/slimebot/level/Level.java
  src/main/java/com/slimebot/level/LevelListener.java
  src/main/java/com/slimebot/level/RankCard.java
  src/main/java/com/slimebot/main/BuildInfo.java
  src/main/java/com/slimebot/main/CommandContext.java
  src/main/java/com/slimebot/main/Database.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/main/config/Config.java
  src/main/java/com/slimebot/main/config/LevelConfig.java
  src/main/java/com/slimebot/main/config/guild/GuildConfig.java
  src/main/java/com/slimebot/main/config/guild/LevelGuildConfig.java
  src/main/java/com/slimebot/util/MathUtil.java
  src/main/java/com/slimebot/util/Pair.java
  src/main/resources/font/Ubuntu.ttf
Labels: feature

#74 Config Improvements
  .gitignore
  .idea/runConfigurations/Run.xml
  README.md
  build.gradle
  run_template/.env
  run_template/config
  src/main/java/com/slimebot/alerts/spotify/PodcastListener.java
  src/main/java/com/slimebot/alerts/spotify/SpotifyListener.java
  src/main/java/com/slimebot/commands/SetupCommand.java
  src/main/java/com/slimebot/commands/config/ConfigCommand.java
  src/main/java/com/slimebot/commands/config/FdmdsConfigCommand.java
  src/main/java/com/slimebot/commands/config/GuildConfigCommand.java
  src/main/java/com/slimebot/commands/config/SpotifyConfigCommand.java
  src/main/java/com/slimebot/commands/config/StaffConfigCommand.java
  src/main/java/com/slimebot/commands/config/engine/ConfigCategory.java
  src/main/java/com/slimebot/commands/config/engine/ConfigCategoryCommand.java
  src/main/java/com/slimebot/commands/config/engine/ConfigField.java
  src/main/java/com/slimebot/commands/config/engine/ConfigFieldType.java
  src/main/java/com/slimebot/commands/config/engine/ConfigPropertyCommand.java
  src/main/java/com/slimebot/commands/config/engine/FieldVerification.java
  src/main/java/com/slimebot/commands/config/engine/InstanceProvider.java
  src/main/java/com/slimebot/commands/config/setup/SetupCommand.java
  src/main/java/com/slimebot/commands/config/setup/StaffFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/ConfigFieldFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/CustomSetupFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/SetupMainFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/SetupMenu.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/main/config/Config.java
  src/main/java/com/slimebot/main/config/guild/FdmdsConfig.java
  src/main/java/com/slimebot/main/config/guild/GuildConfig.java
  src/main/java/com/slimebot/main/config/guild/LevelGuildConfig.java
  src/main/java/com/slimebot/main/config/guild/SpotifyNotificationConfig.java
Labels: feature, improve

#80 Fix new config setup system
  src/main/java/com/slimebot/commands/config/setup/engine/ConfigFieldFrame.java
Labels: bug

#86 Level Improments
  .gitignore
  run_template/config
  src/main/java/com/slimebot/commands/config/LevelConfigCommand.java
  src/main/java/com/slimebot/commands/config/engine/ConfigCategoryCommand.java
  src/main/java/com/slimebot/commands/config/engine/ConfigField.java
  src/main/java/com/slimebot/commands/config/engine/ConfigFieldType.java
  src/main/java/com/slimebot/commands/config/engine/ConfigPropertyCommand.java
  src/main/java/com/slimebot/commands/config/setup/engine/ConfigFieldFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/SetupMenu.java
  src/main/java/com/slimebot/commands/level/LeaderboardCommand.java
  src/main/java/com/slimebot/commands/level/LevelCommand.java
  src/main/java/com/slimebot/commands/level/RankCommand.java
  src/main/java/com/slimebot/commands/level/add/AddLevelCommand.java
  src/main/java/com/slimebot/commands/level/add/AddXPCommand.java
  src/main/java/com/slimebot/commands/level/remove/RemoveLevelCommand.java
  src/main/java/com/slimebot/commands/level/remove/RemoveXPCommand.java
  src/main/java/com/slimebot/commands/level/reset/ResetAllCommand.java
  src/main/java/com/slimebot/commands/level/reset/ResetLevelCommand.java
  src/main/java/com/slimebot/commands/level/reset/ResetMessagesCommand.java
  src/main/java/com/slimebot/commands/level/reset/ResetXPCommand.java
  src/main/java/com/slimebot/events/LevelListener.java
  src/main/java/com/slimebot/events/ReadyListener.java
  src/main/java/com/slimebot/graphic/CustomFont.java
  src/main/java/com/slimebot/graphic/Graphic.java
  src/main/java/com/slimebot/level/Level.java
  src/main/java/com/slimebot/level/LevelListener.java
  src/main/java/com/slimebot/level/RankCard.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/main/config/LevelConfig.java
  src/main/java/com/slimebot/main/config/guild/GuildConfig.java
  src/main/java/com/slimebot/main/config/guild/LevelGuildConfig.java
  src/main/java/com/slimebot/util/MathUtil.java
Labels: feature, improve
