Repository SlimeCloud/SlimeBot, pull requests merged in 2023-08, with the labels that each got.

#107 Assign Role at member join
  src/main/java/com/slimebot/commands/config/engine/ConfigArrayPropertyCommand.java
  src/main/java/com/slimebot/commands/config/engine/ConfigArrayPropertyCommandType.java
  src/main/java/com/slimebot/commands/config/engine/ConfigCategoryCommand.java
  src/main/java/com/slimebot/commands/config/engine/ConfigFieldType.java
  src/main/java/com/slimebot/events/MemberJoinListener.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/main/config/guild/AssignRoleConfig.java
  src/main/java/com/slimebot/main/config/guild/GuildConfig.java
Labels: feature

#108 Database
  README.md
  run_template/config
  src/main/java/com/slimebot/alerts/spotify/SpotifyListener.java
  src/main/java/com/slimebot/commands/FdmdsCommand.java
  src/main/java/com/slimebot/commands/config/ConfigCommand.java
  src/main/java/com/slimebot/commands/config/StaffConfigCommand.java
  src/main/java/com/slimebot/commands/config/setup/SetupCommand.java
  src/main/java/com/slimebot/commands/config/setup/StaffFrame.java
  src/main/java/com/slimebot/commands/config/setup/engine/ConfigFieldFrame.java
  src/main/java/com/slimebot/commands/level/LeaderboardCommand.java
  src/main/java/com/slimebot/commands/level/LevelCommand.java
  src/main/java/com/slimebot/commands/level/add/AddLevelCommand.java
  src/main/java/com/slimebot/commands/level/add/AddXPCommand.java
  src/main/java/com/slimebot/commands/level/remove/RemoveLevelCommand.java
  src/main/java/com/slimebot/commands/level/remove/RemoveXPCommand.java
  src/main/java/com/slimebot/database/DataClass.java
  src/main/java/com/slimebot/database/Database.java
  src/main/java/com/slimebot/database/Key.java
  src/main/java/com/slimebot/database/Table.java
  src/main/java/com/slimebot/events/LevelListener.java
  src/main/java/com/slimebot/graphic/CustomFont.java
  src/main/java/com/slimebot/level/Level.java
  src/main/java/com/slimebot/level/RankCard.java
  src/main/java/com/slimebot/main/CommandContext.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/main/config/Config.java
  src/main/java/com/slimebot/main/config/LevelConfig.java
  src/main/java/com/slimebot/message/StaffMessage.java
  src/main/java/com/slimebot/report/Report.java
  src/main/java/com/slimebot/report/list/ReportBlockSet.java
  src/main/java/com/slimebot/report/list/ReportSet.java
  src/main/java/com/slimebot/util/ReflectionUtil.java
Labels: feature, improve

#111 Add quote feature
  build.gradle
  src/main/java/com/slimebot/commands/QuoteCommand.java
  src/main/java/com/slimebot/commands/QuoteMessageCommand.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/main/config/guild/GuildConfig.java
  src/main/java/com/slimebot/main/config/guild/QuoteConfig.java
Labels: new feature
