Repository SlimeCloud/SlimeBot, pull requests merged in 2023-06, with the labels that each got.

#19 rewrite from Python to Java
  .gitignore
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  build.gradle
  src/main/java/com/slimebot/commands/Bug.java
  src/main/java/com/slimebot/commands/BulkAddRole.java
  src/main/java/com/slimebot/commands/ConfigCmd.java
  src/main/java/com/slimebot/commands/Info.java
  src/main/java/com/slimebot/commands/Ping.java
  src/main/java/com/slimebot/events/OnJoin.java
  src/main/java/com/slimebot/events/ReadyEvent.java
  src/main/java/com/slimebot/events/Timeout.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/report/assets/Report.java
  src/main/java/com/slimebot/report/assets/Status.java
  src/main/java/com/slimebot/report/assets/Type.java
  src/main/java/com/slimebot/report/buttons/Close.java
  src/main/java/com/slimebot/report/buttons/DetailDropdown.java
  src/main/java/com/slimebot/report/commands/Blockreport.java
  src/main/java/com/slimebot/report/commands/GetReportDetail.java
  src/main/java/com/slimebot/report/commands/ReportCmd.java
  src/main/java/com/slimebot/report/commands/ReportList.java
  src/main/java/com/slimebot/report/contextmenus/MsgReport.java
  src/main/java/com/slimebot/report/contextmenus/UserReport.java
  src/main/java/com/slimebot/report/modals/CloseReport.java
  src/main/java/com/slimebot/report/modals/ReportModal.java
  src/main/java/com/slimebot/utils/Checks.java
  src/main/java/com/slimebot/utils/Config.java
  src/main/java/com/slimebot/utils/TimeScheduler.java
  src/main/resources/botConfig.yml
  src/main/resources/bug.properties
  src/main/resources/config.properties
Labels: feature

#20 add info how to use the Configs
  README.md
Labels: documentation

#24 Changed Permission Management & Fixed Solve Logging-Error (SLF4J) on Start
  build.gradle
  src/main/java/com/slimebot/commands/ConfigCmd.java
  src/main/java/com/slimebot/main/Main.java
  src/main/resources/logback.xml
Labels: improve

#28 Create Spotify Listener
  build.gradle
  src/main/java/com/slimebot/alerts/spotify/SpotifyListener.java
  src/main/java/com/slimebot/alerts/spotify/SpotifyListenerManager.java
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/utils/DailyTask.java
Labels: feature

#30 Added .env File | fix #25
  .env
  .gitignore
  build.gradle
  src/main/java/com/slimebot/main/Main.java
  src/main/java/com/slimebot/utils/Config.java
Labels: improve

#36 Bot start log | fix #32
  build.gradle
  src/main/java/com/slimebot/events/ReadyEvent.java
Labels: improve
