Repository SlimeCloud/SlimeBot, pull requests merged in 2024-08, with the labels that each got.

#264 New workflow
  .github/workflows/check.yml
  .github/workflows/deploy_beta.yml
  .github/workflows/deploy_production.yml
  Dockerfile
  build.gradle
  rebuild.sh
Labels: type: feature, priority: high

#262 Fix Absence
  src/main/java/de/slimecloud/slimeball/features/staff/MeetingConfig.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/Absence.java
Labels: type: bug, priority: high

#263 Improve level font rendering
  src/main/java/de/slimecloud/slimeball/features/level/card/CardProfileData.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardRenderer.java
Labels: type: improve, type: feature, priority: normal

#265 Fix new workflow
  .github/workflows/deploy_beta.yml
  .github/workflows/deploy_production.yml
  Dockerfile
  rebuild.sh
Labels: type: bug, priority: high

#266 fix BirthdayAlerts
  build.gradle
  src/main/java/de/slimecloud/slimeball/features/birthday/Birthday.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayAlert.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayListener.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayTable.java
  src/main/java/de/slimecloud/slimeball/features/birthday/commands/BirthdayCommand.java
  src/main/java/de/slimecloud/slimeball/features/birthday/commands/RememberBirthdayCommand.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: bug

#268 Disallow using discord cdn links because they expire
  src/main/java/de/slimecloud/slimeball/config/engine/ConfigFieldType.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/card/GuildCardProfile.java
Labels: type: improve, priority: normal

#270 Improve rankcard name rendering
  src/main/java/de/slimecloud/slimeball/features/level/card/CardRenderer.java
  src/main/resources/font/Symbola.ttf
Labels: type: bug, priority: normal

#272 Fix Fdmds user
  src/main/java/de/slimecloud/slimeball/features/fdmds/FdmdsCommand.java
  src/main/java/de/slimecloud/slimeball/features/github/ContributorCommand.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: bug, priority: normal
