Repository SlimeCloud/SlimeBot, pull requests merged in 2024-01, with the labels that each got.

#158 Fix TimeoutListener
  src/main/java/de/slimecloud/slimeball/features/fdmds/FdmdsCommand.java
  src/main/java/de/slimecloud/slimeball/features/moderation/TimeoutListener.java
  src/main/java/de/slimecloud/slimeball/main/SlimeEmoji.java
Labels: type: bug

#156 Card profile improvements
  build.gradle
  lombok.config
  run_template/config
  src/main/java/de/slimecloud/slimeball/config/GuildConfig.java
  src/main/java/de/slimecloud/slimeball/config/LevelConfig.java
  src/main/java/de/slimecloud/slimeball/features/alerts/SpotifyNotificationConfig.java
  src/main/java/de/slimecloud/slimeball/features/fdmds/FdmdsCommand.java
  src/main/java/de/slimecloud/slimeball/features/github/ContributorAcceptedEvent.java
  src/main/java/de/slimecloud/slimeball/features/github/ContributorCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardDataTable.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardDecorationListener.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardDecorationTable.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardPermission.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardProfileData.java
  src/main/java/de/slimecloud/slimeball/features/level/card/DecorationCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/card/Filter.java
  src/main/java/de/slimecloud/slimeball/features/level/card/GuildCardProfile.java
  src/main/java/de/slimecloud/slimeball/features/level/card/GuildCardTable.java
  src/main/java/de/slimecloud/slimeball/features/level/card/RankCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/card/Style.java
  src/main/java/de/slimecloud/slimeball/features/level/card/StyleComponent.java
  src/main/java/de/slimecloud/slimeball/features/level/card/UserCardDecoration.java
  src/main/java/de/slimecloud/slimeball/features/report/commands/ReportCommand.java
  src/main/java/de/slimecloud/slimeball/features/wrapped/DataListener.java
  src/main/java/de/slimecloud/slimeball/features/wrapped/WrappedData.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
  src/main/java/de/slimecloud/slimeball/main/extensions/ColorOptionParser.java
  src/main/java/de/slimecloud/slimeball/main/extensions/IDOptionParser.java
Labels: type: improve, type: feature

#164 Add GuildTypeMapper
  src/main/java/de/slimecloud/slimeball/features/level/Level.java
  src/main/java/de/slimecloud/slimeball/features/level/LevelListener.java
  src/main/java/de/slimecloud/slimeball/features/level/LevelTable.java
  src/main/java/de/slimecloud/slimeball/features/level/card/GuildCardProfile.java
  src/main/java/de/slimecloud/slimeball/features/report/Report.java
  src/main/java/de/slimecloud/slimeball/features/report/ReportBlock.java
  src/main/java/de/slimecloud/slimeball/features/report/ReportBlockTable.java
  src/main/java/de/slimecloud/slimeball/features/report/ReportListener.java
  src/main/java/de/slimecloud/slimeball/features/wrapped/DataListener.java
  src/main/java/de/slimecloud/slimeball/features/wrapped/WrappedData.java
  src/main/java/de/slimecloud/slimeball/features/wrapped/WrappedDataTable.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
  src/main/java/de/slimecloud/slimeball/main/extensions/SnowflakeTypeMapper.java
  src/main/java/de/slimecloud/slimeball/main/extensions/UserSnowflakeTypeMapper.java
Labels: type: improve

#167 Update dependencies
  build.gradle
  src/main/java/de/slimecloud/slimeball/features/level/card/CardDecorationListener.java
  src/main/java/de/slimecloud/slimeball/features/level/commands/LevelCommand.java
  src/main/java/de/slimecloud/slimeball/features/moderation/AutodeleteListener.java
  src/main/java/de/slimecloud/slimeball/features/moderation/TimeoutListener.java
  src/main/java/de/slimecloud/slimeball/features/report/commands/ReportCommand.java
  src/main/java/de/slimecloud/slimeball/features/wrapped/DataListener.java
Labels: type: improve

#168 Decrease spotify logging
  src/main/java/de/slimecloud/slimeball/features/alerts/SpotifyAlert.java
Labels: type: improve

#170 Added package infos
  src/main/java/de/slimecloud/slimeball/config/GuildConfig.java
  src/main/java/de/slimecloud/slimeball/config/package-info.java
  src/main/java/de/slimecloud/slimeball/features/alerts/package-info.java
  src/main/java/de/slimecloud/slimeball/features/fdmds/package-info.java
  src/main/java/de/slimecloud/slimeball/features/general/package-info.java
  src/main/java/de/slimecloud/slimeball/features/github/package-info.java
  src/main/java/de/slimecloud/slimeball/features/level/card/package-info.java
  src/main/java/de/slimecloud/slimeball/features/level/package-info.java
  src/main/java/de/slimecloud/slimeball/features/moderation/package-info.java
  src/main/java/de/slimecloud/slimeball/features/package-info.java
  src/main/java/de/slimecloud/slimeball/features/poll/package-info.java
  src/main/java/de/slimecloud/slimeball/features/quote/package-info.java
  src/main/java/de/slimecloud/slimeball/features/report/package-info.java
  src/main/java/de/slimecloud/slimeball/features/staff/package-info.java
  src/main/java/de/slimecloud/slimeball/features/wrapped/package-info.java
  src/main/java/de/slimecloud/slimeball/main/package-info.java
  src/main/java/de/slimecloud/slimeball/util/package-info.java
Labels: type: documentation

#171 Fix fdmds
  src/main/java/de/slimecloud/slimeball/features/fdmds/FdmdsCommand.java
Labels: type: bug, priority: high

#173 Update Libraries
  build.gradle
  run_template/config
  src/main/java/de/slimecloud/slimeball/config/Config.java
  src/main/java/de/slimecloud/slimeball/config/LogForwarding.java
  src/main/java/de/slimecloud/slimeball/features/level/LevelTable.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardDataTable.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardDecorationTable.java
  src/main/java/de/slimecloud/slimeball/features/level/card/Filter.java
  src/main/java/de/slimecloud/slimeball/features/level/card/GuildCardTable.java
  src/main/java/de/slimecloud/slimeball/features/level/card/UserCardDecoration.java
  src/main/java/de/slimecloud/slimeball/features/report/ReportBlockTable.java
  src/main/java/de/slimecloud/slimeball/features/report/ReportTable.java
  src/main/java/de/slimecloud/slimeball/features/wrapped/WrappedDataTable.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
  src/main/java/de/slimecloud/slimeball/main/extensions/ColorOptionParser.java
  src/main/java/de/slimecloud/slimeball/main/extensions/ColorTypeMapper.java
  src/main/java/de/slimecloud/slimeball/main/extensions/IDOptionParser.java
  src/main/java/de/slimecloud/slimeball/main/extensions/SnowflakeTypeMapper.java
  src/main/java/de/slimecloud/slimeball/util/ReflectionUtil.java
Labels: type: improve, priority: normal

#174 Save xp type
  src/main/java/de/slimecloud/slimeball/features/wrapped/DataListener.java
  src/main/java/de/slimecloud/slimeball/features/wrapped/WrappedData.java
Labels: type: feature

#176 Improve logging for card errors
  src/main/java/de/slimecloud/slimeball/features/level/card/CardProfileData.java
Labels: type: improve

#161 Statistic channel
  src/main/java/de/slimecloud/slimeball/config/GuildConfig.java
  src/main/java/de/slimecloud/slimeball/features/level/package-info.java
  src/main/java/de/slimecloud/slimeball/features/statistic/MemberCount.java
  src/main/java/de/slimecloud/slimeball/features/statistic/RoleMemberCount.java
  src/main/java/de/slimecloud/slimeball/features/statistic/StatisticConfig.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
  src/main/java/de/slimecloud/slimeball/util/StringUtil.java
  src/main/java/de/slimecloud/slimeball/util/types/AtomicString.java
Labels: type: feature

#177 Fix ConfigFieldType#COLOR
  src/main/java/de/slimecloud/slimeball/config/engine/ConfigFieldType.java
Labels: type: bug, priority: high

#180 Meeting fix
  src/main/java/de/slimecloud/slimeball/features/staff/TeamMeeting.java
Labels: type: improve, priority: normal

#179 Add CalculateCommand
  src/main/java/de/slimecloud/slimeball/features/level/commands/CalculateCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/commands/LevelCommand.java
Labels: type: feature, priority: normal

#178 Improve ConfigFieldType modals
  src/main/java/de/slimecloud/slimeball/config/commands/MenuCommand.java
  src/main/java/de/slimecloud/slimeball/config/engine/ConfigFieldType.java
Labels: type: improve, priority: normal

#175 Level fix
  src/main/java/de/slimecloud/slimeball/features/level/LevelListener.java
  src/main/java/de/slimecloud/slimeball/features/level/LevelTable.java
  src/main/java/de/slimecloud/slimeball/features/level/UserGainXPEvent.java
  src/main/java/de/slimecloud/slimeball/features/level/UserLevelUpEvent.java
  src/main/java/de/slimecloud/slimeball/features/moderation/AutodeleteListener.java
  src/main/java/de/slimecloud/slimeball/features/wrapped/DataListener.java
Labels: type: bug, priority: high

#166 Brithday
  build.gradle
  src/main/java/de/slimecloud/slimeball/config/GuildConfig.java
  src/main/java/de/slimecloud/slimeball/features/birthday/Birthday.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayAlert.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayConfig.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayListener.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayTable.java
  src/main/java/de/slimecloud/slimeball/features/birthday/commands/BirthdayCommand.java
  src/main/java/de/slimecloud/slimeball/features/birthday/commands/BirthdayInfoCommand.java
  src/main/java/de/slimecloud/slimeball/features/birthday/commands/ForgetBirthdayCommand.java
  src/main/java/de/slimecloud/slimeball/features/birthday/commands/RememberBirthdayCommand.java
  src/main/java/de/slimecloud/slimeball/features/birthday/event/BirthdayEndEvent.java
  src/main/java/de/slimecloud/slimeball/features/birthday/event/BirthdayEvent.java
  src/main/java/de/slimecloud/slimeball/features/birthday/event/BirthdayRemoveEvent.java
  src/main/java/de/slimecloud/slimeball/features/birthday/event/BirthdaySetEvent.java
  src/main/java/de/slimecloud/slimeball/features/birthday/event/BirthdayStartEvent.java
  src/main/java/de/slimecloud/slimeball/features/staff/MeetingConfig.java
  src/main/java/de/slimecloud/slimeball/main/Main.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
  src/main/java/de/slimecloud/slimeball/util/TimeUtil.java
Labels: type: feature

#183 remove age from birthdays
  src/main/java/de/slimecloud/slimeball/features/birthday/Birthday.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayConfig.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayListener.java
  src/main/java/de/slimecloud/slimeball/features/birthday/commands/BirthdayInfoCommand.java
  src/main/java/de/slimecloud/slimeball/features/birthday/commands/RememberBirthdayCommand.java
Labels: type: improve, priority: high

#184 Update GH Actions
  .github/workflows/check.yml
Labels: type: improve, priority: normal

#185 Try to fix a rare startup issue
  build.gradle
  src/main/java/de/slimecloud/slimeball/config/commands/EnableCommand.java
  src/main/java/de/slimecloud/slimeball/config/commands/MenuCommand.java
  src/main/java/de/slimecloud/slimeball/config/engine/ConfigFieldType.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayTable.java
  src/main/java/de/slimecloud/slimeball/features/github/GitHubAPI.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardDataTable.java
  src/main/java/de/slimecloud/slimeball/features/level/commands/LevelCommand.java
  src/main/java/de/slimecloud/slimeball/features/poll/PollCommand.java
  src/main/java/de/slimecloud/slimeball/features/report/ReportBlockTable.java
  src/main/java/de/slimecloud/slimeball/features/report/ReportTable.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: bug, priority: normal
