Repository SlimeCloud/SlimeBot, pull requests merged in 2024-07, with the labels that each got.

#254 Add Absence Command
  src/main/java/de/slimecloud/slimeball/config/GuildConfig.java
  src/main/java/de/slimecloud/slimeball/features/alerts/spotify/SpotifyAlert.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardCommand.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/Absence.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/AbsenceCommand.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/AbsenceConfig.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/AbsenceSchedule.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/AbsenceTable.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: feature, priority: high

#258 Multi youtube channel support
  run_template/config.json
  src/main/java/de/slimecloud/slimeball/config/YoutubeConfig.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/GuildYoutubeConfig.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/Youtube.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/YoutubeApiErrorEvent.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/YoutubeListener.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/YoutubeVideoEvent.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/model/ResourceId.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/model/Video.java
Labels: type: improve, type: feature, priority: normal

#259 Fix and Improve Absence
  src/main/java/de/slimecloud/slimeball/features/quote/QuoteCommand.java
  src/main/java/de/slimecloud/slimeball/features/staff/MeetingConfig.java
  src/main/java/de/slimecloud/slimeball/features/staff/StaffConfig.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/Absence.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/AbsenceCommand.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/AbsenceConfig.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/AbsenceSchedule.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/AbsenceScheduler.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/AbsenceTable.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
  src/main/java/de/slimecloud/slimeball/main/extensions/DateTypeMapper.java
Labels: type: bug, type: improve, type: feature, priority: high

#260 change limits for fdmds questions
  src/main/java/de/slimecloud/slimeball/features/fdmds/FdmdsCommand.java
Labels: type: improve, priority: high

#261 Fix and improve Absence
  src/main/java/de/slimecloud/slimeball/features/staff/absence/Absence.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/AbsenceCommand.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/AbsenceTable.java
Labels: type: bug, priority: high
