Repository SlimeCloud/SlimeBot, pull requests merged in 2024-03, with the labels that each got.

#192 Add separate config for music notification role
  src/main/java/de/slimecloud/slimeball/features/alerts/SpotifyAlert.java
  src/main/java/de/slimecloud/slimeball/features/alerts/SpotifyNotificationConfig.java
Labels: type: improve, priority: normal

#193 Use DATE_TIME_LONG instead of TIME_LONG
  src/main/java/de/slimecloud/slimeball/features/staff/MeetingConfig.java
Labels: type: bug, priority: high

#195 replace Mee6 commands
  src/main/java/de/slimecloud/slimeball/features/general/SocialsCommand.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: feature, priority: low

#196 Improve badges
  build.gradle
  run_template/config
  src/main/java/de/slimecloud/slimeball/config/LevelConfig.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayTable.java
  src/main/java/de/slimecloud/slimeball/features/fdmds/FdmdsCommand.java
  src/main/java/de/slimecloud/slimeball/features/github/ContributorCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/Level.java
  src/main/java/de/slimecloud/slimeball/features/level/LevelTable.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardDecorationListener.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardDecorationTable.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardProfileData.java
  src/main/java/de/slimecloud/slimeball/features/level/card/DecorationCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/card/UserCardDecoration.java
  src/main/java/de/slimecloud/slimeball/features/level/card/badge/BadgeCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/card/badge/CardBadgeData.java
  src/main/java/de/slimecloud/slimeball/features/level/card/badge/CardBadgeTable.java
  src/main/java/de/slimecloud/slimeball/features/level/commands/RemoveCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/commands/SetCommand.java
  src/main/java/de/slimecloud/slimeball/features/quote/QuoteDeleteListener.java
  src/main/java/de/slimecloud/slimeball/features/wrapped/DataListener.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
  src/main/java/de/slimecloud/slimeball/main/extensions/SnowflakeTypeMapper.java
  src/main/java/de/slimecloud/slimeball/util/StringUtil.java
Labels: type: improve, type: feature, priority: normal

#202 Set spotify thread names
  src/main/java/de/slimecloud/slimeball/features/alerts/SpotifyAlert.java
Labels: type: improve, priority: low

#204 Sort levels by both level and xp
  build.gradle
  src/main/java/de/slimecloud/slimeball/features/level/LevelTable.java
Labels: type: bug, priority: low

#200 Add poll name display and PollEditCommand
  build.gradle
  src/main/java/de/slimecloud/slimeball/features/poll/Poll.java
  src/main/java/de/slimecloud/slimeball/features/poll/PollCommand.java
  src/main/java/de/slimecloud/slimeball/features/poll/PollEditCommand.java
  src/main/java/de/slimecloud/slimeball/features/poll/PollListener.java
  src/main/java/de/slimecloud/slimeball/features/poll/PollTable.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: feature, priority: normal

#210 added .json to config
  README.md
  run_template/config.json
  src/main/java/de/slimecloud/slimeball/main/Main.java
Labels: type: improve, priority: low

#208 Leaderboard
  build.gradle
  src/main/java/de/slimecloud/slimeball/features/level/Leaderboard.java
  src/main/java/de/slimecloud/slimeball/features/level/Level.java
  src/main/java/de/slimecloud/slimeball/features/level/LevelTable.java
  src/main/java/de/slimecloud/slimeball/features/level/LevelUpListener.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardProfileData.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardRenderer.java
  src/main/java/de/slimecloud/slimeball/features/level/card/RankCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/card/badge/CardBadgeData.java
  src/main/java/de/slimecloud/slimeball/features/level/commands/CalculateCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/commands/LeaderboardCommand.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
  src/main/java/de/slimecloud/slimeball/util/graphic/Graphic.java
  src/main/resources/font/DejaVuSans.ttf
  src/main/resources/font/Ubuntu.ttf
Labels: type: bug, type: improve, type: feature, priority: normal

#209 Fix birthday
  src/main/java/de/slimecloud/slimeball/features/birthday/Birthday.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayAlert.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayConfig.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayListener.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayTable.java
  src/main/java/de/slimecloud/slimeball/features/birthday/commands/BirthdayInfoCommand.java
  src/main/java/de/slimecloud/slimeball/features/birthday/commands/RememberBirthdayCommand.java
  src/main/java/de/slimecloud/slimeball/util/TimeUtil.java
Labels: type: bug, priority: high

#212 Rename "Vielleicht" to "Zu Spät" and remove default assignments
  src/main/java/de/slimecloud/slimeball/features/staff/MeetingConfig.java
  src/main/java/de/slimecloud/slimeball/features/staff/TeamMeeting.java
Labels: type: improve, priority: normal

#213 Remove unused test command
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: bug, priority: normal

#201 Youtube Notification
  run_template/config.json
  run_template/credentials
  src/main/java/de/slimecloud/slimeball/config/Config.java
  src/main/java/de/slimecloud/slimeball/config/GuildConfig.java
  src/main/java/de/slimecloud/slimeball/config/YoutubeConfig.java
  src/main/java/de/slimecloud/slimeball/features/alerts/spotify/Spotify.java
  src/main/java/de/slimecloud/slimeball/features/alerts/spotify/SpotifyAlert.java
  src/main/java/de/slimecloud/slimeball/features/alerts/spotify/SpotifyNotificationConfig.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/GuildYoutubeConfig.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/Youtube.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/YoutubeListener.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/YoutubeVideoEvent.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/model/Channel.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/model/ChannelSnippet.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/model/ResourceId.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/model/SearchResult.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/model/SearchResultSnippet.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/model/Video.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/model/VideoSnippet.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: feature, priority: low

#214 Several minor improvements
  src/main/java/de/slimecloud/slimeball/features/quote/QuoteCommand.java
  src/main/java/de/slimecloud/slimeball/features/staff/TeamMeeting.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
  src/main/java/de/slimecloud/slimeball/main/SlimeEmoji.java
Labels: type: improve, priority: low

#219 Allow multiple YoutubeAPI keys
  run_template/credentials
  src/main/java/de/slimecloud/slimeball/config/GuildConfig.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/Youtube.java
  src/main/java/de/slimecloud/slimeball/features/quote/QuoteCommand.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
  src/main/java/de/slimecloud/slimeball/util/MathUtil.java
Labels: type: improve, priority: normal

#220 Cleanup
  src/main/java/de/slimecloud/slimeball/config/ActivityConfig.java
  src/main/java/de/slimecloud/slimeball/config/Config.java
  src/main/java/de/slimecloud/slimeball/config/GuildConfig.java
  src/main/java/de/slimecloud/slimeball/config/commands/MenuCommand.java
  src/main/java/de/slimecloud/slimeball/features/alerts/spotify/SpotifyAlert.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/Youtube.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/YoutubeVideoEvent.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/model/Channel.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/model/Video.java
  src/main/java/de/slimecloud/slimeball/features/github/GitHubAPI.java
  src/main/java/de/slimecloud/slimeball/features/level/Leaderboard.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardProfileData.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardRenderer.java
  src/main/java/de/slimecloud/slimeball/features/staff/TeamMeeting.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
  src/main/java/de/slimecloud/slimeball/main/extensions/ColorOptionParser.java
  src/main/java/de/slimecloud/slimeball/util/ColorUtil.java
  src/main/java/de/slimecloud/slimeball/util/MathUtil.java
  src/main/java/de/slimecloud/slimeball/util/StringUtil.java
  src/main/java/de/slimecloud/slimeball/util/TimeUtil.java
  src/main/java/de/slimecloud/slimeball/util/graphic/CustomFont.java
  src/main/java/de/slimecloud/slimeball/util/graphic/ImageUtil.java
Labels: type: improve, priority: normal

#218 Fix level reset
  src/main/java/de/slimecloud/slimeball/features/level/LevelTable.java
Labels: type: bug, priority: normal
