Repository SlimeCloud/SlimeBot, pull requests merged in 2024-02, with the labels that each got.

#187 Update JEvent
  build.gradle
  src/main/java/de/slimecloud/slimeball/features/level/LevelUpListener.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardDecorationListener.java
  src/main/java/de/slimecloud/slimeball/features/level/commands/LevelCommand.java
  src/main/java/de/slimecloud/slimeball/features/moderation/AutodeleteListener.java
  src/main/java/de/slimecloud/slimeball/features/moderation/TimeoutListener.java
  src/main/java/de/slimecloud/slimeball/features/report/ReportListener.java
  src/main/java/de/slimecloud/slimeball/features/report/commands/ReportCommand.java
  src/main/java/de/slimecloud/slimeball/features/wrapped/DataListener.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: improve, priority: normal

#188 Make member lists sets to enforce uniqueness
  src/main/java/de/slimecloud/slimeball/features/staff/MeetingConfig.java
Labels: type: bug, priority: low

#190 Show actual date for meeting message
  src/main/java/de/slimecloud/slimeball/features/staff/MeetingConfig.java
Labels: type: improve, priority: normal

#191 Make quotes deletable by adding :x: as Reaction
  src/main/java/de/slimecloud/slimeball/features/fdmds/FdmdsCommand.java
  src/main/java/de/slimecloud/slimeball/features/github/ContributorCommand.java
  src/main/java/de/slimecloud/slimeball/features/quote/QuoteCommand.java
  src/main/java/de/slimecloud/slimeball/features/quote/QuoteDeleteEvent.java
  src/main/java/de/slimecloud/slimeball/features/quote/QuoteDeleteListener.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: feature, priority: normal
