Repository SlimeCloud/SlimeBot, pull requests merged in 2024-10, with the labels that each got.

#278 Improve JEvent Usage
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/YoutubeListener.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayListener.java
  src/main/java/de/slimecloud/slimeball/features/level/LevelUpListener.java
Labels: type: improve

#279 Update gradle
  .github/workflows/check.yml
  .github/workflows/deploy_beta.yml
  .github/workflows/deploy_production.yml
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: type: improve, priority: normal

#280 Improve card autocomplete
  src/main/java/de/slimecloud/slimeball/features/level/card/CardCommand.java
  src/main/java/de/slimecloud/slimeball/features/level/card/CardProfileData.java
Labels: type: improve, priority: normal

#281 Fix level color rendering in edge case
  src/main/java/de/slimecloud/slimeball/features/level/card/CardRenderer.java
Labels: type: bug, priority: normal

#282 Change emoji library to avoid jitpack problems
  build.gradle
  src/main/java/de/slimecloud/slimeball/features/wrapped/DataListener.java
Labels: type: improve, priority: normal
