Repository SlimeCloud/SlimeBot, pull requests merged in 2024-06, with the labels that each got.

#249 React to bot pings
  src/main/java/de/slimecloud/slimeball/features/general/PingListener.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: feature, priority: low

#248 Add IdMemory
  src/main/java/de/slimecloud/slimeball/features/StoredId.java
  src/main/java/de/slimecloud/slimeball/features/alerts/IdMemory.java
  src/main/java/de/slimecloud/slimeball/features/alerts/spotify/SpotifyAlert.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/Youtube.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: bug, type: improve, priority: high

#251 Fix youtube id storage
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/Youtube.java
  src/main/java/de/slimecloud/slimeball/features/alerts/youtube/YoutubeListener.java
Labels: type: bug, priority: high

#252 add derschleimi account
  src/main/java/de/slimecloud/slimeball/features/general/SocialsCommand.java
Labels: type: improve, priority: low
