Repository SlimeCloud/SlimeBot, pull requests merged in 2024-11, with the labels that each got.

#285 Ignore holidays without subdivision information
  src/main/java/de/slimecloud/slimeball/features/alerts/holiday/HolidayAlert.java
Labels: type: bug, priority: normal

#283 Improve scheduleDaily to fix time change
  src/main/java/de/slimecloud/slimeball/features/alerts/holiday/HolidayAlert.java
  src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayAlert.java
  src/main/java/de/slimecloud/slimeball/features/fdmds/FdmdsScheduler.java
  src/main/java/de/slimecloud/slimeball/features/staff/absence/AbsenceScheduler.java
  src/main/java/de/slimecloud/slimeball/main/Scheduler.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: bug, priority: normal

#284 Messages
  src/main/java/de/slimecloud/slimeball/config/GuildConfig.java
  src/main/java/de/slimecloud/slimeball/features/message/AutoMessageConfig.java
  src/main/java/de/slimecloud/slimeball/features/message/MessageCommand.java
  src/main/java/de/slimecloud/slimeball/features/staff/StaffConfig.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: feature, priority: normal

#277 Highlights
  src/main/java/de/slimecloud/slimeball/features/general/PingListener.java
  src/main/java/de/slimecloud/slimeball/features/highlights/Highlight.java
  src/main/java/de/slimecloud/slimeball/features/highlights/HighlightCommand.java
  src/main/java/de/slimecloud/slimeball/features/highlights/HighlightListener.java
  src/main/java/de/slimecloud/slimeball/features/highlights/HighlightTable.java
  src/main/java/de/slimecloud/slimeball/features/highlights/event/HighlightEvent.java
  src/main/java/de/slimecloud/slimeball/features/highlights/event/HighlightRemoveEvent.java
  src/main/java/de/slimecloud/slimeball/features/highlights/event/HighlightSetEvent.java
  src/main/java/de/slimecloud/slimeball/features/highlights/event/HighlightTriggeredEvent.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: feature, priority: low

#287 Messages fix
  src/main/java/de/slimecloud/slimeball/features/message/AutoMessageConfig.java
  src/main/java/de/slimecloud/slimeball/features/message/MessageCommand.java
  src/main/java/de/slimecloud/slimeball/features/moderation/MessageListener.java
  src/main/java/de/slimecloud/slimeball/features/staff/StaffConfig.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
Labels: type: bug, type: improve, priority: high

#288 set time to 17:30
  src/main/java/de/slimecloud/slimeball/features/staff/MeetingConfig.java
Labels: type: bug, type: improve, priority: high

#289 Fix fdmds command response
  src/main/java/de/slimecloud/slimeball/features/fdmds/FdmdsCommand.java
Labels: priority: low

#291 Schulfrei -> schulfrei
  src/main/java/de/slimecloud/slimeball/features/alerts/holiday/HolidayAlert.java
Labels: priority: normal, priority: low

#290 Level api
  .github/workflows/deploy_beta.yml
  .github/workflows/deploy_production.yml
  Dockerfile
  build.gradle
  rebuild.sh
  run_template/config.json
  src/main/java/de/slimecloud/slimeball/config/Config.java
  src/main/java/de/slimecloud/slimeball/features/level/Level.java
  src/main/java/de/slimecloud/slimeball/features/level/LevelApi.java
  src/main/java/de/slimecloud/slimeball/main/SlimeBot.java
  src/main/java/de/slimecloud/slimeball/main/api/ErrorResponse.java
  src/main/java/de/slimecloud/slimeball/main/api/ErrorResponseType.java
  src/main/java/de/slimecloud/slimeball/main/api/Server.java
Labels: type: feature, priority: high
